using System;
using SqlFu;
using SqlFu.DDL;

namespace KongresRodziny2015.Models
{
    [Table("Articles", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
    public class Article
    {
        public int ID { get; set; }

        [ColumnOptions(Size = "100")]
        public String Title { get; set; }

        [ColumnOptions(Size = "500")]
        public String ImageURI { get; set; }

        public String FullText { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}