using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SqlFu;
using SqlFu.DDL;

namespace KongresRodziny2015.Models
{
	[Table("Conferences", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
	public class Conference
	{
		public int ID { get; set; }

		[ColumnOptions(Size = "100")]
		public String ParticipantName { get; set; }

		[ColumnOptions(Size = "100")]
		public String Place { get; set; }

		[ColumnOptions(Size = "255")]
		public String MeetOn { get; set; }

		[ColumnOptions(Size = "255")]
		public String Topic { get; set; }

		public String Description { get; set; }
	}
}