using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SqlFu;
using SqlFu.DDL;

namespace KongresRodziny2015.Models
{
	[Table("Cooperators", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
	public class Cooperator
	{
		public int ID { get; set; }

		[ColumnOptions(IsNullable = true, Size = "255")]
		public String SiteUrl { get; set; }

		[ColumnOptions(Size = "255")]
		public String SiteTitle { get; set; }

		[ColumnOptions(Size = "255")]
		public String LogoPath { get; set; }

		[ColumnOptions(IsNullable = true, Size = "255")]
		public String ImageAlt { get; set; }

		[ColumnOptions(Size = "20")]
		public String Type { get; set; }
	}
}