using System;
using SqlFu;
using SqlFu.DDL;

namespace KongresRodziny2015.Models
{
    [Table("Tags", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
    public class Tag
    {
        public int ID { get; set; }

        [ColumnOptions(Size = "100")]
        public String TagName { get; set; }

        [ColumnOptions(IsNullable = true, Size = "255", DefaultValue = "#")]
        public String TagURL { get; set; }
    }
}