using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SqlFu.DDL;
using SqlFu;

namespace KongresRodziny2015.Models
{
	[Table("Workshops", AutoGenerated = true, CreationOptions = IfTableExists.Ignore, PrimaryKey = "ID")]
	public class Workshop
	{
		public int ID { get; set; }

		[ColumnOptions(Size = "255")]
		public String RegisterUrl { get; set; }

		[ColumnOptions(Size = "255")]
		public String Name { get; set; }

		[ColumnOptions(IsNullable = true, Size = "512")]
		public String Subject { get; set; }

		[ColumnOptions(IsNullable = true, Size = "512")]
		public String Instructor { get; set; }

		[ColumnOptions(IsNullable = true, Size = "512")]
		public String Place { get; set; }

		[ColumnOptions(IsNullable = true, Size = "1024")]
		public String MeetOn { get; set; }

		[ColumnOptions(IsNullable = true)]
		public String Definition { get; set; }

		[ColumnOptions(IsNullable = true)]
		public String Description { get; set; }

		[ColumnOptions(IsNullable = true)]
		public String Rules { get; set; }

		[ColumnOptions(IsNullable = true, Size = "512")]
		public String Help { get; set; }
	}
}